import class_car as car

my_new_car = car.Car('mercedes', 'cla 35 amg', 2023)
print(my_new_car.get_descriptive_name())
my_new_car.read_odometer()
my_new_car.update_odometer(23)    
my_new_car.read_odometer()
my_new_car.increment_odometer(100)
my_new_car.read_odometer()
my_new_electric_Car = car.ElectricCar('tesla', 'model y', 2024)
print(my_new_electric_Car.get_descriptive_name())
my_new_electric_Car.read_odometer()
my_new_electric_Car.update_odometer(45)
my_new_electric_Car.read_odometer()
my_new_electric_Car.describe_battery()